#!/bin/bash

# Check write permission
if [ ! -w "/usr/local/bin" ]; then
    echo -e "\033[1;91m[ERROR] Current user doesn't have 'write' permission at 'usr/local/bin'. Try using 'sudo' or change to another user. \033[0m"
    exit 1
fi

# create symbolic link
ln -s ./source/mcserver /usr/local/bin/mcserver
if [ $? -eq 0 ]; then
    echo -e "\033[1;93m[SUCCESS] Symbolic link created. \033[0m"
else
    echo -e "\033[1;91m[ERROR] Symbolic link created failed. \033[0m"
    exit 1
fi
